import { CurrencyOption } from "@/types";

export const CURRENCIES: CurrencyOption[] = [
  { flag: "ae", code: "AED", name: "UAE Dirham" },
  { flag: "ar", code: "ARS", name: "Argentine Peso" },
  { flag: "au", code: "AUD", name: "Australian Dollar" },
  { flag: "bd", code: "BDT", name: "Bangladeshi Taka" },
  { flag: "bg", code: "BGN", name: "Bulgarian Lev" },
  { flag: "bh", code: "BHD", name: "Bahraini Dinar" },
  { flag: "br", code: "BRL", name: "Brazilian Real" },
  { flag: "ca", code: "CAD", name: "Canadian Dollar" },
  { flag: "ch", code: "CHF", name: "Swiss Franc" },
  { flag: "cl", code: "CLP", name: "Chilean Peso" },
  { flag: "cn", code: "CNY", name: "Chinese Yuan" },
  { flag: "co", code: "COP", name: "Colombian Peso" },
  { flag: "cy", code: "CYP", name: "Euro (Cyprus)" },
  { flag: "cz", code: "CZK", name: "Czech Koruna" },
  { flag: "dk", code: "DKK", name: "Danish Krone" },
  { flag: "eg", code: "EGP", name: "Egyptian Pound" },

  { flag: "eu", code: "EUR", name: "Euro", isPopular: true },
  { flag: "gb", code: "GBP", name: "British Pound", isPopular: true },
  { flag: "hk", code: "HKD", name: "Hong Kong Dollar" },
  { flag: "hm", code: "AUD", name: "Australian Dollar" },
  { flag: "hn", code: "HNL", name: "Honduran Lempira" },
  { flag: "hr", code: "HRV", name: "Euro (Croatia)" },
  { flag: "ht", code: "HTG", name: "Haitian Gourde" },
  { flag: "hu", code: "HUF", name: "Hungarian Forint" },
  { flag: "id", code: "IDR", name: "Indonesian Rupiah" },
  { flag: "in", code: "INR", name: "Indian Rupee" },
  { flag: "is", code: "ISK", name: "Icelandic Króna" },
  { flag: "jo", code: "JOD", name: "Jordanian Dinar" },
  { flag: "jp", code: "JPY", name: "Japanese Yen" },
  { flag: "ke", code: "KES", name: "Kenyan Shilling" },
  { flag: "kr", code: "KRW", name: "South Korean Won" },
  { flag: "kw", code: "KWD", name: "Kuwaiti Dinar" },

  { flag: "lb", code: "LBP", name: "Lebanese Pound" },
  { flag: "lc", code: "XCD", name: "East Caribbean Dollar" },
  { flag: "lk", code: "LKR", name: "Sri Lankan Rupee" },
  { flag: "ma", code: "MAD", name: "Moroccan Dirham" },
  { flag: "mx", code: "MXN", name: "Mexican Peso" },
  { flag: "my", code: "MYR", name: "Malaysian Ringgit" },
  { flag: "ng", code: "NGN", name: "Nigerian Naira" },
  { flag: "nz", code: "NZD", name: "New Zealand Dollar" },
  { flag: "no", code: "NOK", name: "Norwegian Krone" },
  { flag: "np", code: "NPR", name: "Nepalese Rupee" },
  { flag: "om", code: "OMR", name: "Omani Rial" },
  { flag: "pe", code: "PEN", name: "Peruvian Sol" },
  { flag: "ph", code: "PHP", name: "Philippine Peso" },
  { flag: "pk", code: "PKR", name: "Pakistani Rupee" },
  { flag: "pl", code: "PLN", name: "Polish Zloty" },
  { flag: "qa", code: "QAR", name: "Qatari Riyal" },

  { flag: "ro", code: "RON", name: "Romanian Leu" },
  { flag: "ru", code: "RUB", name: "Russian Ruble" },
  { flag: "sa", code: "SAR", name: "Saudi Riyal" },
  { flag: "se", code: "SEK", name: "Swedish Krona" },
  { flag: "sg", code: "SGD", name: "Singapore Dollar" },
  { flag: "th", code: "THB", name: "Thai Baht" },
  { flag: "tr", code: "TRY", name: "Turkish Lira" },
  { flag: "tw", code: "TWD", name: "New Taiwan Dollar" },
  { flag: "ua", code: "UAH", name: "Ukrainian Hryvnia" },
  { flag: "us", code: "USD", name: "US Dollar", isPopular: true },
  { flag: "vn", code: "VND", name: "Vietnamese Dong" },
  { flag: "za", code: "ZAR", name: "South African Rand" },
];