import { LiveMarketPair } from "@/types";

export const PAIRS_TO_FETCH: Pick<LiveMarketPair, 'id' | 'symbol' | 'base' | 'quote'>[] = [
  { id: "usd-jpy", symbol: "USD/JPY", base: "USD", quote: "JPY" },
  { id: "gbp-usd", symbol: "GBP/USD", base: "GBP", quote: "USD" },
  { id: "usd-chf", symbol: "USD/CHF", base: "USD", quote: "CHF" },
  { id: "eur-gbp", symbol: "EUR/GBP", base: "EUR", quote: "GBP" },
  { id: "aud-usd", symbol: "AUD/USD", base: "AUD", quote: "USD" },
  { id: "usd-cad", symbol: "USD/CAD", base: "USD", quote: "CAD" },
  { id: "eur-usd", symbol: "EUR/USD", base: "EUR", quote: "USD" },
  { id: "usd-idr", symbol: "USD/IDR", base: "USD", quote: "IDR" },
];

export const LIVE_MARKET_PAIRS: LiveMarketPair[] = [
  {
    id: "usd-jpy",
    symbol: "USD/JPY",
    base: "USD",
    quote: "JPY",
    rate: 157.91,
    change: 0.06,
    percentChange: 0.04,
    isPositive: true,
  },
  {
    id: "gbp-usd",
    symbol: "GBP/USD",
    base: "GBP",
    quote: "USD",
    rate: 1.3575,
    change: -0.003,
    percentChange: -0.22,
    isPositive: false,
  },
  {
    id: "usd-chf",
    symbol: "USD/CHF",
    base: "USD",
    quote: "CHF",
    rate: 0.9898,
    change: 0.0013,
    percentChange: 0.13,
    isPositive: true,
  },
  {
    id: "eur-gbp",
    symbol: "EUR/GBP",
    base: "EUR",
    quote: "GBP",
    rate: 0.8633,
    change: 0.001,
    percentChange: 0.11,
    isPositive: true,
  },
  {
    id: "aud-usd",
    symbol: "AUD/USD",
    base: "AUD",
    quote: "USD",
    rate: 0.7208,
    change: 0.0006,
    percentChange: 0.08,
    isPositive: true,
  },
  {
    id: "usd-cad",
    symbol: "USD/CAD",
    base: "USD",
    quote: "CAD",
    rate: 1.3815,
    change: 0.0005,
    percentChange: 0.04,
    isPositive: true,
  },
  {
    id: "eur-usd",
    symbol: "EUR/USD",
    base: "EUR",
    quote: "USD",
    rate: 1.0852,
    change: -0.0015,
    percentChange: -0.14,
    isPositive: false,
  },
  {
    id: "usd-idr",
    symbol: "USD/IDR",
    base: "USD",
    quote: "IDR",
    rate: 16245.0,
    change: 25.0,
    percentChange: 0.15,
    isPositive: true,
  },
];